services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Elasticr\ServiceBus\ServiceBus\:
        resource: '../../src/ServiceBus'
        exclude:
          - '../../src/ServiceBus/{Command,Contract,Entity,Eventing,Exception,Model,ValueObject}'