services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Elasticr\ServiceBus\Support\:
        resource: '../../src/Support'

    Elasticr\Support\Doctrine\Provider\DoctrineSerializableFactoryProvider: ~

