<?php

declare(strict_types=1);

namespace Tests\Elasticr\ServiceBus\Unit\Flexibee\Factory;

use Cake\Chronos\Chronos;
use Elasticr\ServiceBus\Flexibee\Factory\FlexibeeOrderDtoFactory;
use Elasticr\ServiceBus\ServiceBus\Model\AddressDto;
use Elasticr\ServiceBus\ServiceBus\Model\OrderDto;
use Elasticr\ServiceBus\ServiceBus\Model\OrderItemDto;
use Elasticr\ServiceBus\ServiceBus\Model\OrderNoteDto;
use Elasticr\ServiceBus\ServiceBus\Model\PaymentMethodDto;
use Elasticr\ServiceBus\ServiceBus\Model\ProductDto;
use Elasticr\ServiceBus\ServiceBus\Model\ShippingMethodDto;
use Elasticr\ServiceBus\ServiceBus\Model\VatRateAwareValueDto;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class FlexibeeOrderDtoFactoryTest extends KernelTestCase
{
    /**
     * @test
     */
    public function create_dto_from_data_array(): void
    {
        /** @var FlexibeeOrderDtoFactory $factory */
        $factory = self::getContainer()->get(FlexibeeOrderDtoFactory::class);

        $data = json_decode('{
                "external-ids":["ext:SHOP:12006"],
                "id": "12094",
                "lastUpdate": "2022-10-03T09:01:14.207+02:00",
                "kod": "110122006447",
                "zamekK": "zamek.otevreno",
                "zamekK@showAs": "Otevřeno",
                "cisDosle": "012206919",
                "varSym": "012206919",
                "cisSml": "",
                "datObj": "",
                "cisDodak": "",
                "doprava": "",
                "datVyst": "2022-10-03+02:00",
                "datTermin": "",
                "datReal": "",
                "popis": "",
                "poznam": "null",
                "uvodTxt": "",
                "zavTxt": "",
                "sumOsv": "0.0",
                "sumZklSniz": "21.74",
                "sumZklSniz2": "0.0",
                "sumZklZakl": "114.05",
                "sumZklCelkem": "135.79",
                "sumDphSniz": "3.26",
                "sumDphSniz2": "0.0",
                "sumDphZakl": "23.95",
                "sumDphCelkem": "27.21",
                "sumCelkSniz": "25.0",
                "sumCelkSniz2": "0.0",
                "sumCelkZakl": "138.0",
                "sumCelkem": "163.0",
                "sumOsvMen": "0.0",
                "sumZklSnizMen": "0.0",
                "sumZklSniz2Men": "0.0",
                "sumZklZaklMen": "0.0",
                "sumZklCelkemMen": "0.0",
                "sumDphZaklMen": "0.0",
                "sumDphSnizMen": "0.0",
                "sumDphSniz2Men": "0.0",
                "sumDphCelkemMen": "0.0",
                "sumCelkSnizMen": "0.0",
                "sumCelkSniz2Men": "0.0",
                "sumCelkZaklMen": "0.0",
                "sumCelkemMen": "0.0",
                "sumNaklady": "10.59",
                "slevaDokl": "0.0",
                "kurz": "0.0",
                "kurzMnozstvi": "0.0",
                "stavUzivK": "stavDoklObch.pripraveno",
                "stavUzivK@showAs": "Připraveno",
                "nazFirmy": "Test Test",
                "ulice": "Testovací 123",
                "mesto": "Plzeň",
                "psc": "32600",
                "eanKod": "",
                "ic": "",
                "dic": "",
                "pocetPriloh": "0",
                "postovniShodna": "true",
                "faNazev": "",
                "faNazev2": "",
                "faUlice": "",
                "faMesto": "",
                "faPsc": "",
                "faEanKod": "",
                "bezPolozek": "false",
                "szbDphSniz": "15.0",
                "szbDphSniz2": "10.0",
                "szbDphZakl": "21.0",
                "storno": "false",
                "zaokrJakSumK": "zaokrJak.matem",
                "zaokrJakSumK@showAs": "matematicky",
                "zaokrNaSumK": "zaokrNa.jednotky",
                "zaokrNaSumK@showAs": "1",
                "zaokrJakDphK": "zaokrJak.matem",
                "zaokrJakDphK@showAs": "matematicky",
                "zaokrNaDphK": "zaokrNa.zadne",
                "zaokrNaDphK@showAs": "nezaokrouhlovat",
                "metodaZaokrDoklK": "metodaZaokr.0sazba",
                "metodaZaokrDoklK@showAs": "do 0 sazby",
                "vytvaretKorPol": "false",
                "stitky": "TSE",
                "typDokl": "code:PO-CZ",
                "typDokl@ref": "/c/prodietix_s_r_o_abra_staging/typ-objednavky-prijate/23.json",
                "typDokl@showAs": "PO-CZ: Přijatá objednávka - CZ",
                "mena": "code:CZK",
                "mena@ref": "/c/prodietix_s_r_o_abra_staging/mena/31.json",
                "mena@showAs": "CZK: Česká koruna",
                "konSym": "",
                "firma": "code:O12006",
                "firma@ref": "/c/prodietix_s_r_o_abra_staging/adresar/873.json",
                "firma@showAs": "O12006: Test Test",
                "stat": "code:CZ",
                "stat@ref": "/c/prodietix_s_r_o_abra_staging/stat/39.json",
                "stat@showAs": "Česká republika",
                "faStat": "",
                "mistUrc": "",
                "bankovniUcet": "",
                "typDoklBan": "",
                "statDph": "code:CZ",
                "statDph@ref": "/c/prodietix_s_r_o_abra_staging/stat/39.json",
                "statDph@showAs": "Česká republika",
                "stredisko": "code:01-CZ",
                "stredisko@ref": "/c/prodietix_s_r_o_abra_staging/stredisko/2.json",
                "stredisko@showAs": "01-CZ: CZ",
                "cinnost": "",
                "zakazka": "",
                "uzivatel": "code:rtsoft",
                "uzivatel@ref": "/c/prodietix_s_r_o_abra_staging/uzivatel/7.json",
                "uzivatel@showAs": "rtsoft",
                "zodpOsoba": "code:rtsoft",
                "zodpOsoba@ref": "/c/prodietix_s_r_o_abra_staging/uzivatel/7.json",
                "zodpOsoba@showAs": "rtsoft",
                "kontaktOsoba": "",
                "kontaktJmeno": "",
                "kontaktEmail": "skarda@rtsoft.cz",
                "kontaktTel": "702291956",
                "rada": "code:PO-CZ",
                "rada@showAs": "PO-CZ: Přijatá objednávka - CZ",
                "rada@if-not-found": "null",
                "rada@ref": "/c/prodietix_s_r_o_abra_staging/rada-objednavky-prijate/14.json",
                "smlouva": "",
                "formaDopravy": "code:GLS-BUSINESS",
                "formaDopravy@ref": "/c/prodietix_s_r_o_abra_staging/forma-dopravy/18.json",
                "formaDopravy@showAs": "GLS-BUSINESS: GLS Business",
                "uuid": "7b27a77f3d7d767e2dd7bf3cf974341198c1d1d8",
                "source": "",
                "balikPocet": "0",
                "branchId": "1234",
                "formaUhradyCis": "code:COD",
                "formaUhradyCis@ref": "/c/prodietix_s_r_o_abra_staging/forma-uhrady/5.json",
                "formaUhradyCis@showAs": "COD: Dobírkou",
                "procReal": "0.0",
                "faktSouhrn": "false",
                "faktTxt": "",
                "typDoklNabFak": "code:VF-CZ",
                "typDoklNabFak@ref": "/c/prodietix_s_r_o_abra_staging/typ-faktury-vydane/6.json",
                "typDoklNabFak@showAs": "VF-CZ: Vydaná faktura - CZ",
                "stavDoklObch": "code:PRIPRAVENO",
                "stavDoklObch@ref": "/c/prodietix_s_r_o_abra_staging/stav-obchodniho-dokladu/2.json",
                "stavDoklObch@showAs": "PRIPRAVENO: Připraveno",
                "skladCil": "",
                "items":[
                    {
                    "external-ids":["ext:SHOP:155012"],
                    "id": "234412",
                    "lastUpdate": "2022-10-03T09:01:14.208+02:00",
                    "kod": "42120053",
                    "eanKod": "",
                    "nazev": "Krémová polévka s kuřecí příchutí",
                    "nazevA": "Hydinová polievka",
                    "nazevB": "Geflügelsuppe",
                    "nazevC": "Baromfileves",
                    "cisRad": "1",
                    "typPolozkyK": "typPolozky.katalog",
                    "typPolozkyK@showAs": "Položka z ceníku",
                    "baleniId": "0",
                    "mnozBaleni": "0.0",
                    "mnozMj": "1.0",
                    "typCenyDphK": "typCeny.sDph",
                    "typCenyDphK@showAs": "včetně DPH",
                    "typSzbDphK": "typSzbDph.dphSniz",
                    "typSzbDphK@showAs": "snížená",
                    "szbDph": "15.0",
                    "cenaMj": "25.0",
                    "slevaPol": "0.0",
                    "uplSlevaDokl": "false",
                    "sumZkl": "21.74",
                    "sumDph": "3.26",
                    "sumCelkem": "25.0",
                    "sumZklMen": "0.0",
                    "sumDphMen": "0.0",
                    "sumCelkemMen": "0.0",
                    "objem": "0.0",
                    "cenJednotka": "1.0",
                    "cenaMjNakup": "10.590822",
                    "cenaMjProdej": "59.0",
                    "cenaMjCenikTuz": "59.0",
                    "objednatK": "",
                    "rezervovat": "true",
                    "mnozMjPlan": "0.0",
                    "mnozMjReal": "0.0",
                    "mnozMjZbyva": "1.0",
                    "vyrobce": "",
                    "autoZaokr": "false",
                    "autogen": "false",
                    "poznam": "",
                    "slevaDokl": "0.0",
                    "datVyst": "2022-10-03+02:00",
                    "kopZakazku": "true",
                    "kopStred": "true",
                    "kopCinnost": "true",
                    "kopKlice": "true",
                    "storno": "false",
                    "stornoPol": "false",
                    "sklad": "code:SKLAD-CZ",
                    "sklad@ref": "/c/prodietix_s_r_o_abra_staging/sklad/5.json",
                    "sklad@showAs": "SKLAD-CZ: Sklad - CZ",
                    "stredisko": "code:01-CZ",
                    "stredisko@ref": "/c/prodietix_s_r_o_abra_staging/stredisko/2.json",
                    "stredisko@showAs": "01-CZ: CZ",
                    "cinnost": "",
                    "mena": "code:CZK",
                    "mena@ref": "/c/prodietix_s_r_o_abra_staging/mena/31.json",
                    "mena@showAs": "CZK: Česká koruna",
                    "zakazka": "",
                    "dodavatel": "code:SAS0",
                    "dodavatel@ref": "/c/prodietix_s_r_o_abra_staging/adresar/645.json",
                    "dodavatel@showAs": "SAS0: SAS BARIATRIX EUROPE INC",
                    "cenik": "code:42120053",
                    "cenik@ref": "/c/prodietix_s_r_o_abra_staging/cenik/109.json",
                    "cenik@showAs": "42120053: Krémová polévka s kuřecí příchutí",
                    "cenHlad": "",
                    "mj": "code:KS",
                    "mj@ref": "/c/prodietix_s_r_o_abra_staging/merna-jednotka/3.json",
                    "mj@showAs": "KS: kus",
                    "mjObjem": "",
                    "sazbaDph": "22",
                    "sazbaDph@showAs": "15 %",
                    "sazbaDph@if-not-found": "null",
                    "sazbaDph@ref": "/c/prodietix_s_r_o_abra_staging/sazba-dph/22.json",
                    "idPolObchZdroj": "",
                    "stitky": "",
                    "source": "109",
                    "marze": "105.27",
                    "minMarze": "0.0",
                    "doklObch": "code:110122006447",
                    "doklObch@ref": "/c/prodietix_s_r_o_abra_staging/objednavka-prijata/12094.json",
                    "doklObch@showAs": "110122006447",
                    "rezervovatMj": "1.0",
                    "objednanoMj": "0.0",
                    "poplatekParentPolObch": "",
                    "neseskupovatObj": "false",
                    "datTermin": "",
                    "kopDatTermin": "true"
                    },
                    {
                    "external-ids":["ext:SHOP:155013"],
                    "id": "234413",
                    "lastUpdate": "2022-10-03T09:01:14.208+02:00",
                    "kod": "SHIPPING_GLS",
                    "eanKod": "",
                    "nazev": "GLS Business",
                    "nazevA": "GLS",
                    "nazevB": "GLS",
                    "nazevC": "GLS",
                    "cisRad": "2",
                    "typPolozkyK": "typPolozky.katalog",
                    "typPolozkyK@showAs": "Položka z ceníku",
                    "baleniId": "0",
                    "mnozBaleni": "0.0",
                    "mnozMj": "1.0",
                    "typCenyDphK": "typCeny.sDph",
                    "typCenyDphK@showAs": "včetně DPH",
                    "typSzbDphK": "typSzbDph.dphZakl",
                    "typSzbDphK@showAs": "základní",
                    "szbDph": "21.0",
                    "cenaMj": "99.0",
                    "slevaPol": "0.0",
                    "uplSlevaDokl": "false",
                    "sumZkl": "81.82",
                    "sumDph": "17.18",
                    "sumCelkem": "99.0",
                    "sumZklMen": "0.0",
                    "sumDphMen": "0.0",
                    "sumCelkemMen": "0.0",
                    "objem": "0.0",
                    "cenJednotka": "1.0",
                    "cenaMjNakup": "0.0",
                    "cenaMjProdej": "99.0",
                    "cenaMjCenikTuz": "99.0",
                    "objednatK": "",
                    "rezervovat": "false",
                    "mnozMjPlan": "0.0",
                    "mnozMjReal": "0.0",
                    "mnozMjZbyva": "1.0",
                    "vyrobce": "",
                    "autoZaokr": "false",
                    "autogen": "false",
                    "poznam": "",
                    "slevaDokl": "0.0",
                    "datVyst": "2022-10-03+02:00",
                    "kopZakazku": "true",
                    "kopStred": "true",
                    "kopCinnost": "true",
                    "kopKlice": "true",
                    "storno": "false",
                    "stornoPol": "false",
                    "sklad": "",
                    "stredisko": "code:01-CZ",
                    "stredisko@ref": "/c/prodietix_s_r_o_abra_staging/stredisko/2.json",
                    "stredisko@showAs": "01-CZ: CZ",
                    "cinnost": "",
                    "mena": "code:CZK",
                    "mena@ref": "/c/prodietix_s_r_o_abra_staging/mena/31.json",
                    "mena@showAs": "CZK: Česká koruna",
                    "zakazka": "",
                    "dodavatel": "",
                    "cenik": "code:SHIPPING_GLS",
                    "cenik@ref": "/c/prodietix_s_r_o_abra_staging/cenik/171.json",
                    "cenik@showAs": "SHIPPING_GLS: Doprava GLS",
                    "cenHlad": "",
                    "mj": "",
                    "mjObjem": "",
                    "sazbaDph": "23",
                    "sazbaDph@showAs": "21 %",
                    "sazbaDph@if-not-found": "null",
                    "sazbaDph@ref": "/c/prodietix_s_r_o_abra_staging/sazba-dph/23.json",
                    "idPolObchZdroj": "",
                    "stitky": "",
                    "source": "36",
                    "marze": "0.0",
                    "minMarze": "0.0",
                    "doklObch": "code:110122006447",
                    "doklObch@ref": "/c/prodietix_s_r_o_abra_staging/objednavka-prijata/12094.json",
                    "doklObch@showAs": "110122006447",
                    "rezervovatMj": "0.0",
                    "objednanoMj": "0.0",
                    "poplatekParentPolObch": "",
                    "neseskupovatObj": "false",
                    "datTermin": "",
                    "kopDatTermin": "true"
                    },
                    {
                    "external-ids":["ext:SHOP:155014"],
                    "id": "234414",
                    "lastUpdate": "2022-10-03T09:01:14.209+02:00",
                    "kod": "COD",
                    "eanKod": "",
                    "nazev": "Dobírka CZ",
                    "nazevA": "",
                    "nazevB": "",
                    "nazevC": "Utánvétel",
                    "cisRad": "3",
                    "typPolozkyK": "typPolozky.katalog",
                    "typPolozkyK@showAs": "Položka z ceníku",
                    "baleniId": "0",
                    "mnozBaleni": "0.0",
                    "mnozMj": "1.0",
                    "typCenyDphK": "typCeny.sDph",
                    "typCenyDphK@showAs": "včetně DPH",
                    "typSzbDphK": "typSzbDph.dphZakl",
                    "typSzbDphK@showAs": "základní",
                    "szbDph": "21.0",
                    "cenaMj": "39.0",
                    "slevaPol": "0.0",
                    "uplSlevaDokl": "false",
                    "sumZkl": "32.23",
                    "sumDph": "6.77",
                    "sumCelkem": "39.0",
                    "sumZklMen": "0.0",
                    "sumDphMen": "0.0",
                    "sumCelkemMen": "0.0",
                    "objem": "0.0",
                    "cenJednotka": "1.0",
                    "cenaMjNakup": "0.0",
                    "cenaMjProdej": "39.0",
                    "cenaMjCenikTuz": "39.0",
                    "objednatK": "",
                    "rezervovat": "false",
                    "mnozMjPlan": "0.0",
                    "mnozMjReal": "0.0",
                    "mnozMjZbyva": "1.0",
                    "vyrobce": "",
                    "autoZaokr": "false",
                    "autogen": "false",
                    "poznam": "",
                    "slevaDokl": "0.0",
                    "datVyst": "2022-10-03+02:00",
                    "kopZakazku": "true",
                    "kopStred": "true",
                    "kopCinnost": "true",
                    "kopKlice": "true",
                    "storno": "false",
                    "stornoPol": "false",
                    "sklad": "",
                    "stredisko": "code:01-CZ",
                    "stredisko@ref": "/c/prodietix_s_r_o_abra_staging/stredisko/2.json",
                    "stredisko@showAs": "01-CZ: CZ",
                    "cinnost": "",
                    "mena": "code:CZK",
                    "mena@ref": "/c/prodietix_s_r_o_abra_staging/mena/31.json",
                    "mena@showAs": "CZK: Česká koruna",
                    "zakazka": "",
                    "dodavatel": "",
                    "cenik": "code:COD",
                    "cenik@ref": "/c/prodietix_s_r_o_abra_staging/cenik/170.json",
                    "cenik@showAs": "COD: Dobírka",
                    "cenHlad": "",
                    "mj": "",
                    "mjObjem": "",
                    "sazbaDph": "23",
                    "sazbaDph@showAs": "21 %",
                    "sazbaDph@if-not-found": "null",
                    "sazbaDph@ref": "/c/prodietix_s_r_o_abra_staging/sazba-dph/23.json",
                    "idPolObchZdroj": "",
                    "stitky": "",
                    "source": "33",
                    "marze": "0.0",
                    "minMarze": "0.0",
                    "doklObch": "code:110122006447",
                    "doklObch@ref": "/c/prodietix_s_r_o_abra_staging/objednavka-prijata/12094.json",
                    "doklObch@showAs": "110122006447",
                    "rezervovatMj": "0.0",
                    "objednanoMj": "0.0",
                    "poplatekParentPolObch": "",
                    "neseskupovatObj": "false",
                    "datTermin": "",
                    "kopDatTermin": "true"
                    }
                ]
            }', true, 512, JSON_THROW_ON_ERROR);

        $data['items'][0]['cenikDto'] = new ProductDto(169, '42120053', 'Krémová polévka s kuřecí příchutí', 0, 0, 0, 0, '', 1, 'typZasoby.zbozi', 'ZBOZI');
        $data['items'][1]['cenikDto'] = new ProductDto(171, 'GLS', 'GLS', 0, 0, 0, 0, '', 0, 'typZasoby.sluzba', 'DOPRAVA');
        $data['items'][2]['cenikDto'] = new ProductDto(170, 'COD', 'Dobírka', 0, 0, 0, 0, '', 0, 'typZasoby.sluzba', 'PLATBY');

        $dtoBillingAddress = new AddressDto('Test Test', 'Test', 'Test', 'Testovací 123', '', 'Plzeň', '32600', 'CZ', 'skarda@rtsoft.cz', '702291956', '', '');
        $dtoPayment = new PaymentMethodDto('COD', 'COD: Dobírkou', new VatRateAwareValueDto(32.23, 39, 21));
        $dtoShippingMethod = new ShippingMethodDto('GLS-BUSINESS', 'GLS-BUSINESS: GLS Business', new VatRateAwareValueDto(81.82, 99, 21), '1234');
        $items = [];
        $items[] = new OrderItemDto(234412, '42120053', 'Krémová polévka s kuřecí příchutí', 1.0, 'KS', 25.0, 21.74, 15, 3.26, null, 0, 1);

        $dto = new OrderDto(
            12094,
            '110122006447',
            $dtoBillingAddress,
            null,
            $dtoPayment,
            $dtoShippingMethod,
            'Připraveno',
            '',
            163.0,
            135.79,
            'CZK',
            $items,
            Chronos::createFromFormat('Y-m-d', '2022-10-03'),
            new OrderNoteDto(''),
            null,
            [],
            '012206919'
        );

        $this->assertEquals($dto, $factory->createFromApiResponse($data));
    }

    /**
     * @test
     */
    public function create_dto_from_data_array_wrong_shipping_address(): void
    {
        /** @var FlexibeeOrderDtoFactory $factory */
        $factory = self::getContainer()->get(FlexibeeOrderDtoFactory::class);

        $data = json_decode('{
                "external-ids": [
                    "ext:SHOP:14411"
                ],
                "id": "14383",
                "lastUpdate": "2022-10-28T11:22:13.212+02:00",
                "kod": "110122007964",
                "zamekK": "zamek.otevreno",
                "zamekK@showAs": "Otevřeno",
                "cisDosle": "012208479",
                "varSym": "012208479",
                "cisSml": "",
                "datObj": "",
                "cisDodak": "",
                "doprava": "",
                "datVyst": "2022-10-28+02:00",
                "datTermin": "",
                "datReal": "",
                "popis": "",
                "poznam": "",
                "uvodTxt": "",
                "zavTxt": "",
                "sumOsv": "0.0",
                "sumZklSniz": "11457.96",
                "sumZklSniz2": "0.0",
                "sumZklZakl": "32.23",
                "sumZklCelkem": "11490.19",
                "sumDphSniz": "1718.04",
                "sumDphSniz2": "0.0",
                "sumDphZakl": "6.77",
                "sumDphCelkem": "1724.81",
                "sumCelkSniz": "13176.0",
                "sumCelkSniz2": "0.0",
                "sumCelkZakl": "39.0",
                "sumCelkem": "13215.0",
                "sumOsvMen": "0.0",
                "sumZklSnizMen": "0.0",
                "sumZklSniz2Men": "0.0",
                "sumZklZaklMen": "0.0",
                "sumZklCelkemMen": "0.0",
                "sumDphZaklMen": "0.0",
                "sumDphSnizMen": "0.0",
                "sumDphSniz2Men": "0.0",
                "sumDphCelkemMen": "0.0",
                "sumCelkSnizMen": "0.0",
                "sumCelkSniz2Men": "0.0",
                "sumCelkZaklMen": "0.0",
                "sumCelkemMen": "0.0",
                "sumNaklady": "3882.33",
                "slevaDokl": "0.0",
                "kurz": "0.0",
                "kurzMnozstvi": "0.0",
                "stavUzivK": "stavDoklObch.pripraveno",
                "stavUzivK@showAs": "Připraveno",
                "nazFirmy": "Eva Kohoutková",
                "ulice": "Smetanova 740",
                "mesto": "Šternberk",
                "psc": "78501",
                "eanKod": "",
                "ic": "",
                "dic": "",
                "pocetPriloh": "0",
                "postovniShodna": "false",
                "faNazev": "null",
                "faNazev2": "",
                "faUlice": "Olomoucká 173",
                "faMesto": "Šternberk",
                "faPsc": "78501",
                "faEanKod": "",
                "bezPolozek": "false",
                "szbDphSniz": "15.0",
                "szbDphSniz2": "10.0",
                "szbDphZakl": "21.0",
                "storno": "false",
                "zaokrJakSumK": "zaokrJak.matem",
                "zaokrJakSumK@showAs": "matematicky",
                "zaokrNaSumK": "zaokrNa.jednotky",
                "zaokrNaSumK@showAs": "1",
                "zaokrJakDphK": "zaokrJak.matem",
                "zaokrJakDphK@showAs": "matematicky",
                "zaokrNaDphK": "zaokrNa.zadne",
                "zaokrNaDphK@showAs": "nezaokrouhlovat",
                "metodaZaokrDoklK": "metodaZaokr.0sazba",
                "metodaZaokrDoklK@showAs": "do 0 sazby",
                "vytvaretKorPol": "false",
                "stitky": "TSE",
                "typDokl": "code:PO-CZ",
                "typDokl@ref": "/c/prodietix_s_r_o_/typ-objednavky-prijate/23.json",
                "typDokl@showAs": "PO-CZ: Přijatá objednávka - CZ",
                "mena": "code:CZK",
                "mena@ref": "/c/prodietix_s_r_o_/mena/31.json",
                "mena@showAs": "CZK: Česká koruna",
                "konSym": "",
                "firma": "code:U143",
                "firma@ref": "/c/prodietix_s_r_o_/adresar/1992.json",
                "firma@showAs": "U143: Eva Kohoutková",
                "stat": "code:CZ",
                "stat@ref": "/c/prodietix_s_r_o_/stat/39.json",
                "stat@showAs": "Česká republika",
                "faStat": "code:CZ",
                "faStat@ref": "/c/prodietix_s_r_o_/stat/39.json",
                "faStat@showAs": "Česká republika",
                "mistUrc": "",
                "bankovniUcet": "",
                "typDoklBan": "",
                "statDph": "code:CZ",
                "statDph@ref": "/c/prodietix_s_r_o_/stat/39.json",
                "statDph@showAs": "Česká republika",
                "stredisko": "code:01-CZ",
                "stredisko@ref": "/c/prodietix_s_r_o_/stredisko/2.json",
                "stredisko@showAs": "01-CZ: CZ",
                "cinnost": "",
                "zakazka": "",
                "uzivatel": "code:rtsoft",
                "uzivatel@ref": "/c/prodietix_s_r_o_/uzivatel/7.json",
                "uzivatel@showAs": "rtsoft",
                "zodpOsoba": "code:rtsoft",
                "zodpOsoba@ref": "/c/prodietix_s_r_o_/uzivatel/7.json",
                "zodpOsoba@showAs": "rtsoft",
                "kontaktOsoba": "",
                "kontaktJmeno": "",
                "kontaktEmail": "kohoutkovae@seznam.cz",
                "kontaktTel": "727874227",
                "rada": "code:PO-CZ",
                "rada@showAs": "PO-CZ: Přijatá objednávka - CZ",
                "rada@if-not-found": "null",
                "rada@ref": "/c/prodietix_s_r_o_/rada-objednavky-prijate/14.json",
                "smlouva": "",
                "formaDopravy": "code:PPL-PRIVATE",
                "formaDopravy@ref": "/c/prodietix_s_r_o_/forma-dopravy/27.json",
                "formaDopravy@showAs": "PPL-PRIVATE: PPL Private",
                "uuid": "e3fbd1bcf5c554b66a99aa30fd148e417d4433f2",
                "source": "",
                "balikPocet": "0",
                "branchId": "null",
                "formaUhradyCis": "code:COD",
                "formaUhradyCis@ref": "/c/prodietix_s_r_o_/forma-uhrady/5.json",
                "formaUhradyCis@showAs": "COD: Dobírkou",
                "procReal": "0.0",
                "faktSouhrn": "false",
                "faktTxt": "",
                "typDoklNabFak": "code:VF-CZ",
                "typDoklNabFak@ref": "/c/prodietix_s_r_o_/typ-faktury-vydane/6.json",
                "typDoklNabFak@showAs": "VF-CZ: Vydaná faktura - CZ",
                "stavDoklObch": "code:PRIPRAVENO",
                "stavDoklObch@ref": "/c/prodietix_s_r_o_/stav-obchodniho-dokladu/2.json",
                "stavDoklObch@showAs": "PRIPRAVENO: Připraveno",
                "skladCil": "",
                "items":[
                    {
                    "external-ids":["ext:SHOP:155012"],
                    "id": "234412",
                    "lastUpdate": "2022-10-03T09:01:14.208+02:00",
                    "kod": "42120053",
                    "eanKod": "",
                    "nazev": "Krémová polévka s kuřecí příchutí",
                    "nazevA": "Hydinová polievka",
                    "nazevB": "Geflügelsuppe",
                    "nazevC": "Baromfileves",
                    "cisRad": "1",
                    "typPolozkyK": "typPolozky.katalog",
                    "typPolozkyK@showAs": "Položka z ceníku",
                    "baleniId": "0",
                    "mnozBaleni": "0.0",
                    "mnozMj": "1.0",
                    "typCenyDphK": "typCeny.sDph",
                    "typCenyDphK@showAs": "včetně DPH",
                    "typSzbDphK": "typSzbDph.dphSniz",
                    "typSzbDphK@showAs": "snížená",
                    "szbDph": "15.0",
                    "cenaMj": "25.0",
                    "slevaPol": "0.0",
                    "uplSlevaDokl": "false",
                    "sumZkl": "21.74",
                    "sumDph": "3.26",
                    "sumCelkem": "25.0",
                    "sumZklMen": "0.0",
                    "sumDphMen": "0.0",
                    "sumCelkemMen": "0.0",
                    "objem": "0.0",
                    "cenJednotka": "1.0",
                    "cenaMjNakup": "10.590822",
                    "cenaMjProdej": "59.0",
                    "cenaMjCenikTuz": "59.0",
                    "objednatK": "",
                    "rezervovat": "true",
                    "mnozMjPlan": "0.0",
                    "mnozMjReal": "0.0",
                    "mnozMjZbyva": "1.0",
                    "vyrobce": "",
                    "autoZaokr": "false",
                    "autogen": "false",
                    "poznam": "",
                    "slevaDokl": "0.0",
                    "datVyst": "2022-10-03+02:00",
                    "kopZakazku": "true",
                    "kopStred": "true",
                    "kopCinnost": "true",
                    "kopKlice": "true",
                    "storno": "false",
                    "stornoPol": "false",
                    "sklad": "code:SKLAD-CZ",
                    "sklad@ref": "/c/prodietix_s_r_o_abra_staging/sklad/5.json",
                    "sklad@showAs": "SKLAD-CZ: Sklad - CZ",
                    "stredisko": "code:01-CZ",
                    "stredisko@ref": "/c/prodietix_s_r_o_abra_staging/stredisko/2.json",
                    "stredisko@showAs": "01-CZ: CZ",
                    "cinnost": "",
                    "mena": "code:CZK",
                    "mena@ref": "/c/prodietix_s_r_o_abra_staging/mena/31.json",
                    "mena@showAs": "CZK: Česká koruna",
                    "zakazka": "",
                    "dodavatel": "code:SAS0",
                    "dodavatel@ref": "/c/prodietix_s_r_o_abra_staging/adresar/645.json",
                    "dodavatel@showAs": "SAS0: SAS BARIATRIX EUROPE INC",
                    "cenik": "code:42120053",
                    "cenik@ref": "/c/prodietix_s_r_o_abra_staging/cenik/109.json",
                    "cenik@showAs": "42120053: Krémová polévka s kuřecí příchutí",
                    "cenHlad": "",
                    "mj": "code:KS",
                    "mj@ref": "/c/prodietix_s_r_o_abra_staging/merna-jednotka/3.json",
                    "mj@showAs": "KS: kus",
                    "mjObjem": "",
                    "sazbaDph": "22",
                    "sazbaDph@showAs": "15 %",
                    "sazbaDph@if-not-found": "null",
                    "sazbaDph@ref": "/c/prodietix_s_r_o_abra_staging/sazba-dph/22.json",
                    "idPolObchZdroj": "",
                    "stitky": "",
                    "source": "109",
                    "marze": "105.27",
                    "minMarze": "0.0",
                    "doklObch": "code:110122006447",
                    "doklObch@ref": "/c/prodietix_s_r_o_abra_staging/objednavka-prijata/12094.json",
                    "doklObch@showAs": "110122006447",
                    "rezervovatMj": "1.0",
                    "objednanoMj": "0.0",
                    "poplatekParentPolObch": "",
                    "neseskupovatObj": "false",
                    "datTermin": "",
                    "kopDatTermin": "true"
                    },
                    {
                    "external-ids":["ext:SHOP:155013"],
                    "id": "234413",
                    "lastUpdate": "2022-10-03T09:01:14.208+02:00",
                    "kod": "SHIPPING_GLS",
                    "eanKod": "",
                    "nazev": "GLS Business",
                    "nazevA": "GLS",
                    "nazevB": "GLS",
                    "nazevC": "GLS",
                    "cisRad": "2",
                    "typPolozkyK": "typPolozky.katalog",
                    "typPolozkyK@showAs": "Položka z ceníku",
                    "baleniId": "0",
                    "mnozBaleni": "0.0",
                    "mnozMj": "1.0",
                    "typCenyDphK": "typCeny.sDph",
                    "typCenyDphK@showAs": "včetně DPH",
                    "typSzbDphK": "typSzbDph.dphZakl",
                    "typSzbDphK@showAs": "základní",
                    "szbDph": "21.0",
                    "cenaMj": "99.0",
                    "slevaPol": "0.0",
                    "uplSlevaDokl": "false",
                    "sumZkl": "81.82",
                    "sumDph": "17.18",
                    "sumCelkem": "99.0",
                    "sumZklMen": "0.0",
                    "sumDphMen": "0.0",
                    "sumCelkemMen": "0.0",
                    "objem": "0.0",
                    "cenJednotka": "1.0",
                    "cenaMjNakup": "0.0",
                    "cenaMjProdej": "99.0",
                    "cenaMjCenikTuz": "99.0",
                    "objednatK": "",
                    "rezervovat": "false",
                    "mnozMjPlan": "0.0",
                    "mnozMjReal": "0.0",
                    "mnozMjZbyva": "1.0",
                    "vyrobce": "",
                    "autoZaokr": "false",
                    "autogen": "false",
                    "poznam": "",
                    "slevaDokl": "0.0",
                    "datVyst": "2022-10-03+02:00",
                    "kopZakazku": "true",
                    "kopStred": "true",
                    "kopCinnost": "true",
                    "kopKlice": "true",
                    "storno": "false",
                    "stornoPol": "false",
                    "sklad": "",
                    "stredisko": "code:01-CZ",
                    "stredisko@ref": "/c/prodietix_s_r_o_abra_staging/stredisko/2.json",
                    "stredisko@showAs": "01-CZ: CZ",
                    "cinnost": "",
                    "mena": "code:CZK",
                    "mena@ref": "/c/prodietix_s_r_o_abra_staging/mena/31.json",
                    "mena@showAs": "CZK: Česká koruna",
                    "zakazka": "",
                    "dodavatel": "",
                    "cenik": "code:SHIPPING_GLS",
                    "cenik@ref": "/c/prodietix_s_r_o_abra_staging/cenik/171.json",
                    "cenik@showAs": "SHIPPING_GLS: Doprava GLS",
                    "cenHlad": "",
                    "mj": "",
                    "mjObjem": "",
                    "sazbaDph": "23",
                    "sazbaDph@showAs": "21 %",
                    "sazbaDph@if-not-found": "null",
                    "sazbaDph@ref": "/c/prodietix_s_r_o_abra_staging/sazba-dph/23.json",
                    "idPolObchZdroj": "",
                    "stitky": "",
                    "source": "36",
                    "marze": "0.0",
                    "minMarze": "0.0",
                    "doklObch": "code:110122006447",
                    "doklObch@ref": "/c/prodietix_s_r_o_abra_staging/objednavka-prijata/12094.json",
                    "doklObch@showAs": "110122006447",
                    "rezervovatMj": "0.0",
                    "objednanoMj": "0.0",
                    "poplatekParentPolObch": "",
                    "neseskupovatObj": "false",
                    "datTermin": "",
                    "kopDatTermin": "true"
                    },
                    {
                    "external-ids":["ext:SHOP:155014"],
                    "id": "234414",
                    "lastUpdate": "2022-10-03T09:01:14.209+02:00",
                    "kod": "COD",
                    "eanKod": "",
                    "nazev": "Dobírka CZ",
                    "nazevA": "",
                    "nazevB": "",
                    "nazevC": "Utánvétel",
                    "cisRad": "3",
                    "typPolozkyK": "typPolozky.katalog",
                    "typPolozkyK@showAs": "Položka z ceníku",
                    "baleniId": "0",
                    "mnozBaleni": "0.0",
                    "mnozMj": "1.0",
                    "typCenyDphK": "typCeny.sDph",
                    "typCenyDphK@showAs": "včetně DPH",
                    "typSzbDphK": "typSzbDph.dphZakl",
                    "typSzbDphK@showAs": "základní",
                    "szbDph": "21.0",
                    "cenaMj": "39.0",
                    "slevaPol": "0.0",
                    "uplSlevaDokl": "false",
                    "sumZkl": "32.23",
                    "sumDph": "6.77",
                    "sumCelkem": "39.0",
                    "sumZklMen": "0.0",
                    "sumDphMen": "0.0",
                    "sumCelkemMen": "0.0",
                    "objem": "0.0",
                    "cenJednotka": "1.0",
                    "cenaMjNakup": "0.0",
                    "cenaMjProdej": "39.0",
                    "cenaMjCenikTuz": "39.0",
                    "objednatK": "",
                    "rezervovat": "false",
                    "mnozMjPlan": "0.0",
                    "mnozMjReal": "0.0",
                    "mnozMjZbyva": "1.0",
                    "vyrobce": "",
                    "autoZaokr": "false",
                    "autogen": "false",
                    "poznam": "",
                    "slevaDokl": "0.0",
                    "datVyst": "2022-10-03+02:00",
                    "kopZakazku": "true",
                    "kopStred": "true",
                    "kopCinnost": "true",
                    "kopKlice": "true",
                    "storno": "false",
                    "stornoPol": "false",
                    "sklad": "",
                    "stredisko": "code:01-CZ",
                    "stredisko@ref": "/c/prodietix_s_r_o_abra_staging/stredisko/2.json",
                    "stredisko@showAs": "01-CZ: CZ",
                    "cinnost": "",
                    "mena": "code:CZK",
                    "mena@ref": "/c/prodietix_s_r_o_abra_staging/mena/31.json",
                    "mena@showAs": "CZK: Česká koruna",
                    "zakazka": "",
                    "dodavatel": "",
                    "cenik": "code:COD",
                    "cenik@ref": "/c/prodietix_s_r_o_abra_staging/cenik/170.json",
                    "cenik@showAs": "COD: Dobírka",
                    "cenHlad": "",
                    "mj": "",
                    "mjObjem": "",
                    "sazbaDph": "23",
                    "sazbaDph@showAs": "21 %",
                    "sazbaDph@if-not-found": "null",
                    "sazbaDph@ref": "/c/prodietix_s_r_o_abra_staging/sazba-dph/23.json",
                    "idPolObchZdroj": "",
                    "stitky": "",
                    "source": "33",
                    "marze": "0.0",
                    "minMarze": "0.0",
                    "doklObch": "code:110122006447",
                    "doklObch@ref": "/c/prodietix_s_r_o_abra_staging/objednavka-prijata/12094.json",
                    "doklObch@showAs": "110122006447",
                    "rezervovatMj": "0.0",
                    "objednanoMj": "0.0",
                    "poplatekParentPolObch": "",
                    "neseskupovatObj": "false",
                    "datTermin": "",
                    "kopDatTermin": "true"
                    }
                ]
            }', true, 512, JSON_THROW_ON_ERROR);

        $data['items'][0]['cenikDto'] = new ProductDto(169, '42120053', 'Krémová polévka s kuřecí příchutí', 0, 0, 0, 0, '', 1, 'typZasoby.zbozi', 'ZBOZI');
        $data['items'][1]['cenikDto'] = new ProductDto(171, 'GLS', 'GLS', 0, 0, 0, 0, '', 0, 'typZasoby.sluzba', 'DOPRAVA');
        $data['items'][2]['cenikDto'] = new ProductDto(170, 'COD', 'Dobírka', 0, 0, 0, 0, '', 0, 'typZasoby.sluzba', 'PLATBY');

        $dtoBillingAddress = new AddressDto(
            'Eva Kohoutková',
            'Eva',
            'Kohoutková',
            'Smetanova 740',
            '',
            'Šternberk',
            '78501',
            'CZ',
            'kohoutkovae@seznam.cz',
            '727874227',
            '',
            ''
        );
        $dtoShippingAddress = new AddressDto(
            'Eva Kohoutková',
            'Eva',
            'Kohoutková',
            'Olomoucká 173',
            '',
            'Šternberk',
            '78501',
            'CZ',
            'kohoutkovae@seznam.cz',
            '727874227',
            '',
            ''
        );
        $dtoPayment = new PaymentMethodDto('COD', 'COD: Dobírkou', new VatRateAwareValueDto(32.23, 39, 21));
        $dtoShippingMethod = new ShippingMethodDto('PPL-PRIVATE', 'PPL-PRIVATE: PPL Private', new VatRateAwareValueDto(81.82, 99, 21), null);
        $items = [];
        $items[] = new OrderItemDto(234412, '42120053', 'Krémová polévka s kuřecí příchutí', 1.0, 'KS', 25.0, 21.74, 15, 3.26, null, 0, 1);

        $dto = new OrderDto(
            14383,
            '110122007964',
            $dtoBillingAddress,
            $dtoShippingAddress,
            $dtoPayment,
            $dtoShippingMethod,
            'Připraveno',
            '',
            13215.0,
            11490.19,
            'CZK',
            $items,
            Chronos::createFromFormat('Y-m-d', '2022-10-28'),
            new OrderNoteDto(''),
            null,
            [],
            '012208479'
        );

        $this->assertEquals($dto, $factory->createFromApiResponse($data));
    }
}
